#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.demo.model
  mapperLocations: classpath:mapper/*.xml
---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/person
    username: root
    password: 321
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource